//
//  PaintCodeImages.m
//  Longboxed-iOS
//
//  Created by Jay Hickey on 2/3/15.
//  Copyright (c) 2015 Jay Hickey. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "PaintCodeImages.h"


@implementation PaintCodeImages

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawPlusWithColor: (UIColor*)color width: (CGFloat)width;
{

    //// Frames
    CGRect frame = CGRectMake(0, 0, width, width);


    //// Shape Drawing
    UIBezierPath* shapePath = UIBezierPath.bezierPath;
    [shapePath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 1.00000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47883 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52117 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47883 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52117 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00000 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.48208 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.00000 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.48208 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47883 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.00000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47883 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.00000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52117 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.48208 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52117 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.48208 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 1.00000 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52117 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 1.00000 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52117 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52117 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 1.00000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52117 * CGRectGetHeight(frame))];
    [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 1.00000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47883 * CGRectGetHeight(frame))];
    [shapePath closePath];
    shapePath.miterLimit = 4;

    shapePath.usesEvenOddFillRule = YES;

    [color setFill];
    [shapePath fill];
}

+ (void)drawArrowWithColor: (UIColor*)color width: (CGFloat)width;
{

    //// Frames
    CGRect frame = CGRectMake(0, 0, width, 28);

    //// Subframes
    CGRect page = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.01144 - 0.07) + 0.57, CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.03410 - 0.22) + 0.72, floor(CGRectGetWidth(frame) * 0.98675 + 0.16) - floor(CGRectGetWidth(frame) * 0.01144 - 0.07) - 0.23, floor(CGRectGetHeight(frame) * 0.90272 + 0.45) - floor(CGRectGetHeight(frame) * 0.03410 - 0.22) - 0.68);


    //// Page-
    {
        //// Rectangle- Drawing
        UIBezierPath* rectanglePath = UIBezierPath.bezierPath;
        [rectanglePath moveToPoint: CGPointMake(CGRectGetMinX(page) + 0.04331 * CGRectGetWidth(page), CGRectGetMinY(page) + 1.00000 * CGRectGetHeight(page))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(page) + 0.00000 * CGRectGetWidth(page), CGRectGetMinY(page) + 0.92029 * CGRectGetHeight(page))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(page) + 0.50000 * CGRectGetWidth(page), CGRectGetMinY(page) + 0.00000 * CGRectGetHeight(page))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(page) + 1.00000 * CGRectGetWidth(page), CGRectGetMinY(page) + 0.92029 * CGRectGetHeight(page))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(page) + 0.95770 * CGRectGetWidth(page), CGRectGetMinY(page) + 0.99814 * CGRectGetHeight(page))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(page) + 0.50101 * CGRectGetWidth(page), CGRectGetMinY(page) + 0.15756 * CGRectGetHeight(page))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(page) + 0.04331 * CGRectGetWidth(page), CGRectGetMinY(page) + 1.00000 * CGRectGetHeight(page))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(page) + 0.04331 * CGRectGetWidth(page), CGRectGetMinY(page) + 1.00000 * CGRectGetHeight(page))];
        [rectanglePath closePath];
        rectanglePath.miterLimit = 4;

        rectanglePath.usesEvenOddFillRule = YES;

        [color setFill];
        [rectanglePath fill];
    }
}

+ (void)drawLongboxedLogoWithColor: (UIColor*)color width: (CGFloat)width;
{

    //// Frames
    CGRect frame = CGRectMake(1, 1, width, width);

    //// Subframes
    CGRect group4 = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.01800 - 0.4) + 0.9, CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.01120 + 0.46) + 0.04, floor(CGRectGetWidth(frame) * 0.98957 + 0.02) - floor(CGRectGetWidth(frame) * 0.01800 - 0.4) - 0.42, floor(CGRectGetHeight(frame) * 0.99920 + 0.06) - floor(CGRectGetHeight(frame) * 0.01120 + 0.46) + 0.4);


    //// Group 4
    {
        //// Shape Drawing
        UIBezierPath* shapePath = UIBezierPath.bezierPath;
        [shapePath moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.64654 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.45352 * CGRectGetHeight(group4))];
        [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.35495 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.45352 * CGRectGetHeight(group4))];
        [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.29855 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.50555 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.32340 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.45352 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.29855 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.47645 * CGRectGetHeight(group4))];
        [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.35495 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.55758 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.29855 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.53465 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.32340 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.55758 * CGRectGetHeight(group4))];
        [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.64654 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.55758 * CGRectGetHeight(group4))];
        [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.70294 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.50555 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.67809 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.55758 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.70294 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.53465 * CGRectGetHeight(group4))];
        [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.64654 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.45352 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.70294 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.47645 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.67809 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.45352 * CGRectGetHeight(group4))];
        [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.64654 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.45352 * CGRectGetHeight(group4))];
        [shapePath closePath];
        shapePath.miterLimit = 4;

        shapePath.usesEvenOddFillRule = YES;

        [color setFill];
        [shapePath fill];


        //// Shape 2 Drawing
        UIBezierPath* shape2Path = UIBezierPath.bezierPath;
        [shape2Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.92352 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.00000 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.07553 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.00000 * CGRectGetHeight(group4))];
        [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.00000 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.06966 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.03346 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.00000 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.00000 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.03086 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.00000 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.25220 * CGRectGetHeight(group4))];
        [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.05927 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.32011 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.00000 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.28571 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.02486 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.31305 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.05927 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89242 * CGRectGetHeight(group4))];
        [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.17591 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 1.00000 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.05927 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.95150 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.11185 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 1.00000 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.82409 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 1.00000 * CGRectGetHeight(group4))];
        [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.94073 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89242 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.88815 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 1.00000 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.94073 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.95150 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.94073 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.32011 * CGRectGetHeight(group4))];
        [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 1.00000 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.25220 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.97419 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.31305 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 1.00000 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.28571 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 1.00000 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.06966 * CGRectGetHeight(group4))];
        [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.92352 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.00000 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.99904 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.03175 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.96558 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.00000 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.92352 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.00000 * CGRectGetHeight(group4))];
        [shape2Path closePath];
        [shape2Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.11281 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.10406 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.88623 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.10406 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.88623 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.21693 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.11281 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.21693 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.11281 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.10406 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.11281 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.10406 * CGRectGetHeight(group4))];
        [shape2Path closePath];
        [shape2Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.82409 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89594 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.17591 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89594 * CGRectGetHeight(group4))];
        [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.17208 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89242 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.17400 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89594 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.17208 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89418 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.17208 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.32187 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.82696 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.32187 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.82696 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89242 * CGRectGetHeight(group4))];
        [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.82409 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89594 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.82696 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89418 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.82600 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89594 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.82409 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89594 * CGRectGetHeight(group4))];
        [shape2Path closePath];
        shape2Path.miterLimit = 4;

        shape2Path.usesEvenOddFillRule = YES;

        [color setFill];
        [shape2Path fill];
    }
}

+ (void)drawMagnifyingGlassWithColor: (UIColor*)color width: (CGFloat)width;
{

    //// Frames
    CGRect frame = CGRectMake(0, 0, width, width);

    //// Subframes
    CGRect group = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.02000 - 0.5) + 1, CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.02000 + 0.25) + 0.25, floor(CGRectGetWidth(frame) * 0.97546 - 0.27) - floor(CGRectGetWidth(frame) * 0.02000 - 0.5) - 0.23, floor(CGRectGetHeight(frame) * 0.99500 - 0.5) - floor(CGRectGetHeight(frame) * 0.02000 + 0.25) + 0.75);


    //// Group
    {
        //// Oval Drawing
        UIBezierPath* ovalPath = UIBezierPath.bezierPath;
        [ovalPath moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.64395 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.63853 * CGRectGetHeight(group))];
        [ovalPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.64395 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15946 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.77739 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50614 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.77739 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.29185 * CGRectGetHeight(group))];
        [ovalPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.15882 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.15946 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.51007 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.02664 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.29270 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.02664 * CGRectGetHeight(group))];
        [ovalPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.15882 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.63853 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.02538 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.29185 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.02538 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.50614 * CGRectGetHeight(group))];
        [ovalPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.64395 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.63853 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.29270 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.77135 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.51007 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.77135 * CGRectGetHeight(group))];
        [ovalPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.68493 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.68141 * CGRectGetHeight(group))];
        [ovalPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.11784 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.68141 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.52825 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.83685 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.27453 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.83685 * CGRectGetHeight(group))];
        [ovalPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.11784 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11658 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + -0.03928 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.52553 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + -0.03928 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.27246 * CGRectGetHeight(group))];
        [ovalPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.68493 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.11658 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.27453 * CGRectGetWidth(group), CGRectGetMinY(group) + -0.03886 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.52825 * CGRectGetWidth(group), CGRectGetMinY(group) + -0.03886 * CGRectGetHeight(group))];
        [ovalPath addCurveToPoint: CGPointMake(CGRectGetMinX(group) + 0.68493 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.68141 * CGRectGetHeight(group)) controlPoint1: CGPointMake(CGRectGetMinX(group) + 0.84205 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.27246 * CGRectGetHeight(group)) controlPoint2: CGPointMake(CGRectGetMinX(group) + 0.84205 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.52553 * CGRectGetHeight(group))];
        [ovalPath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.64395 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.63853 * CGRectGetHeight(group))];
        [ovalPath closePath];
        [color setFill];
        [ovalPath fill];


        //// Rectangle Drawing
        UIBezierPath* rectanglePath = UIBezierPath.bezierPath;
        [rectanglePath moveToPoint: CGPointMake(CGRectGetMinX(group) + 0.93848 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 1.00000 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.93770 * CGRectGetHeight(group))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.71676 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.65086 * CGRectGetHeight(group))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.65523 * CGRectGetWidth(group), CGRectGetMinY(group) + 0.71316 * CGRectGetHeight(group))];
        [rectanglePath addLineToPoint: CGPointMake(CGRectGetMinX(group) + 0.93848 * CGRectGetWidth(group), CGRectGetMinY(group) + 1.00000 * CGRectGetHeight(group))];
        [rectanglePath closePath];
        [color setFill];
        [rectanglePath fill];
        [color setStroke];
        rectanglePath.lineWidth = 0.5;
        [rectanglePath stroke];
    }
}

+ (void)drawDefaultCoverWithColor: (UIColor*)color background: (UIColor*)background width: (CGFloat)width height: (CGFloat)height;
{

    //// Frames
    CGRect frame = CGRectMake(1, 1, width, height);

    //// Subframes
    CGRect group4 = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.08000 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * 0.22667 - 0.1) + 0.6, floor(CGRectGetWidth(frame) * 0.89157 - 0.08) - floor(CGRectGetWidth(frame) * 0.08000 + 0.5) + 0.58, floor(CGRectGetHeight(frame) * 0.77867 + 0.5) - floor(CGRectGetHeight(frame) * 0.22667 - 0.1) - 0.6);


    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(CGRectGetMinX(frame) - 1, CGRectGetMinY(frame), floor((CGRectGetWidth(frame) + 1) * 1.00000 + 0.5), floor((CGRectGetHeight(frame)) * 1.00000 + 0.5))];
    [background setFill];
    [rectanglePath fill];


    //// Group 4
    {
        //// Shape Drawing
        UIBezierPath* shapePath = UIBezierPath.bezierPath;
        [shapePath moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.64654 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.45352 * CGRectGetHeight(group4))];
        [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.35495 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.45352 * CGRectGetHeight(group4))];
        [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.29855 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.50555 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.32340 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.45352 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.29855 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.47645 * CGRectGetHeight(group4))];
        [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.35495 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.55758 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.29855 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.53465 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.32340 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.55758 * CGRectGetHeight(group4))];
        [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.64654 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.55758 * CGRectGetHeight(group4))];
        [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.70294 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.50555 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.67809 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.55758 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.70294 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.53465 * CGRectGetHeight(group4))];
        [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.64654 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.45352 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.70294 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.47645 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.67809 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.45352 * CGRectGetHeight(group4))];
        [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.64654 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.45352 * CGRectGetHeight(group4))];
        [shapePath closePath];
        shapePath.miterLimit = 4;

        shapePath.usesEvenOddFillRule = YES;

        [color setFill];
        [shapePath fill];


        //// Shape 2 Drawing
        UIBezierPath* shape2Path = UIBezierPath.bezierPath;
        [shape2Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.92352 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.00000 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.07553 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.00000 * CGRectGetHeight(group4))];
        [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.00000 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.06966 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.03346 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.00000 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.00000 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.03086 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.00000 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.25220 * CGRectGetHeight(group4))];
        [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.05927 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.32011 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.00000 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.28571 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.02486 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.31305 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.05927 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89242 * CGRectGetHeight(group4))];
        [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.17591 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 1.00000 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.05927 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.95150 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.11185 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 1.00000 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.82409 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 1.00000 * CGRectGetHeight(group4))];
        [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.94073 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89242 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.88815 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 1.00000 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.94073 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.95150 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.94073 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.32011 * CGRectGetHeight(group4))];
        [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 1.00000 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.25220 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.97419 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.31305 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 1.00000 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.28571 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 1.00000 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.06966 * CGRectGetHeight(group4))];
        [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.92352 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.00000 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.99904 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.03175 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.96558 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.00000 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.92352 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.00000 * CGRectGetHeight(group4))];
        [shape2Path closePath];
        [shape2Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.11281 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.10406 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.88623 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.10406 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.88623 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.21693 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.11281 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.21693 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.11281 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.10406 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.11281 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.10406 * CGRectGetHeight(group4))];
        [shape2Path closePath];
        [shape2Path moveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.82409 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89594 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.17591 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89594 * CGRectGetHeight(group4))];
        [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.17208 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89242 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.17400 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89594 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.17208 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89418 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.17208 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.32187 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.82696 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.32187 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.82696 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89242 * CGRectGetHeight(group4))];
        [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(group4) + 0.82409 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89594 * CGRectGetHeight(group4)) controlPoint1: CGPointMake(CGRectGetMinX(group4) + 0.82696 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89418 * CGRectGetHeight(group4)) controlPoint2: CGPointMake(CGRectGetMinX(group4) + 0.82600 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89594 * CGRectGetHeight(group4))];
        [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(group4) + 0.82409 * CGRectGetWidth(group4), CGRectGetMinY(group4) + 0.89594 * CGRectGetHeight(group4))];
        [shape2Path closePath];
        shape2Path.miterLimit = 4;

        shape2Path.usesEvenOddFillRule = YES;

        [color setFill];
        [shape2Path fill];
    }
}

+ (void)drawLongboxedTextWithLogoTextColor: (UIColor*)logoTextColor logoWidth: (CGFloat)logoWidth;
{

    //// Frames
    CGRect frame = CGRectMake(0, 1, logoWidth, 34);

    //// Subframes
    CGRect page1 = CGRectMake(CGRectGetMinX(frame) + floor(CGRectGetWidth(frame) * 0.00000 + 0.5), CGRectGetMinY(frame) + floor(CGRectGetHeight(frame) * -0.02941 + 0.25) + 0.25, floor(CGRectGetWidth(frame) * 1.00000 + 0.5) - floor(CGRectGetWidth(frame) * 0.00000 + 0.5) + 0, floor(CGRectGetHeight(frame) * 0.99279 + 0.5) - floor(CGRectGetHeight(frame) * -0.02941 + 0.25) - 0.25);


    //// Page-1
    {
        //// longboxed_full
        {
            //// Group 4
            {
                //// Shape Drawing
                UIBezierPath* shapePath = UIBezierPath.bezierPath;
                [shapePath moveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.11466 * CGRectGetHeight(page1))];
                [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.01044 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00832 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.05530 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.00461 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00832 * CGRectGetHeight(page1))];
                [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.02088 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.11466 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.01627 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00832 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.02088 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.05530 * CGRectGetHeight(page1))];
                [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.02088 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.79007 * CGRectGetHeight(page1))];
                [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.05953 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.79007 * CGRectGetHeight(page1))];
                [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.06902 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.88678 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.06482 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.79007 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.06902 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.83289 * CGRectGetHeight(page1))];
                [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.05953 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98343 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.06902 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.94061 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.06482 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98343 * CGRectGetHeight(page1))];
                [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.01044 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98343 * CGRectGetHeight(page1))];
                [shapePath addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.87711 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.00461 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98343 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.93647 * CGRectGetHeight(page1))];
                [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.11466 * CGRectGetHeight(page1))];
                [shapePath addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.11466 * CGRectGetHeight(page1))];
                [shapePath closePath];
                shapePath.miterLimit = 4;

                shapePath.usesEvenOddFillRule = YES;

                [logoTextColor setFill];
                [shapePath fill];


                //// Shape 2 Drawing
                UIBezierPath* shape2Path = UIBezierPath.bezierPath;
                [shape2Path moveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.08786 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50278 * CGRectGetHeight(page1))];
                [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.08786 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50001 * CGRectGetHeight(page1))];
                [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.13844 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00000 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.08786 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.22515 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.10915 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00000 * CGRectGetHeight(page1))];
                [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.18875 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.49725 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.16773 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00000 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.18875 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.22239 * CGRectGetHeight(page1))];
                [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.18875 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50001 * CGRectGetHeight(page1))];
                [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.13817 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 1.00000 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.18875 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.77488 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.16746 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 1.00000 * CGRectGetHeight(page1))];
                [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.08786 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50278 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.10888 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 1.00003 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.08786 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.77764 * CGRectGetHeight(page1))];
                [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.08786 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50278 * CGRectGetHeight(page1))];
                [shape2Path closePath];
                [shape2Path moveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.16691 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50278 * CGRectGetHeight(page1))];
                [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.16691 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50001 * CGRectGetHeight(page1))];
                [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.13817 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.19614 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.16691 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.33425 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.15498 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.19614 * CGRectGetHeight(page1))];
                [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.10969 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.49725 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.12135 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.19614 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.10969 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.33149 * CGRectGetHeight(page1))];
                [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.10969 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50001 * CGRectGetHeight(page1))];
                [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.13844 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.80388 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.10969 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.66575 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.12162 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.80388 * CGRectGetHeight(page1))];
                [shape2Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.16691 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50278 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.15526 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.80388 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.16691 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.66854 * CGRectGetHeight(page1))];
                [shape2Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.16691 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50278 * CGRectGetHeight(page1))];
                [shape2Path closePath];
                shape2Path.miterLimit = 4;

                shape2Path.usesEvenOddFillRule = YES;

                [logoTextColor setFill];
                [shape2Path fill];


                //// Shape 3 Drawing
                UIBezierPath* shape3Path = UIBezierPath.bezierPath;
                [shape3Path moveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.22088 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.11745 * CGRectGetHeight(page1))];
                [shape3Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.23132 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.01108 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.22088 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.05806 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.22549 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.01108 * CGRectGetHeight(page1))];
                [shape3Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.23349 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.01108 * CGRectGetHeight(page1))];
                [shape3Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.24434 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.07323 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.23850 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.01108 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.24149 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.03597 * CGRectGetHeight(page1))];
                [shape3Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.28461 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.61194 * CGRectGetHeight(page1))];
                [shape3Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.28461 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.11331 * CGRectGetHeight(page1))];
                [shape3Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.29491 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00834 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.28461 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.05530 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.28922 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00834 * CGRectGetHeight(page1))];
                [shape3Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.30522 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.11331 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.30061 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00834 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.30522 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.05533 * CGRectGetHeight(page1))];
                [shape3Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.30522 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.88264 * CGRectGetHeight(page1))];
                [shape3Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.29478 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98898 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.30522 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.94202 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.30061 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98898 * CGRectGetHeight(page1))];
                [shape3Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.29410 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98898 * CGRectGetHeight(page1))];
                [shape3Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.28325 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.92683 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.28909 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98898 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.28610 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.96412 * CGRectGetHeight(page1))];
                [shape3Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.24149 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.36881 * CGRectGetHeight(page1))];
                [shape3Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.24149 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.88678 * CGRectGetHeight(page1))];
                [shape3Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.23118 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.99174 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.24149 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.94478 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.23688 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.99174 * CGRectGetHeight(page1))];
                [shape3Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.22088 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.88678 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.22549 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.99174 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.22088 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.94476 * CGRectGetHeight(page1))];
                [shape3Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.22088 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.11745 * CGRectGetHeight(page1))];
                [shape3Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.22088 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.11745 * CGRectGetHeight(page1))];
                [shape3Path closePath];
                shape3Path.miterLimit = 4;

                shape3Path.usesEvenOddFillRule = YES;

                [logoTextColor setFill];
                [shape3Path fill];


                //// Shape 4 Drawing
                UIBezierPath* shape4Path = UIBezierPath.bezierPath;
                [shape4Path moveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.33735 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50278 * CGRectGetHeight(page1))];
                [shape4Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.33735 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50001 * CGRectGetHeight(page1))];
                [shape4Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.38712 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00000 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.33735 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.22515 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.35837 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00000 * CGRectGetHeight(page1))];
                [shape4Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.41953 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.09394 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.40149 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00000 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.41098 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.03315 * CGRectGetHeight(page1))];
                [shape4Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.42387 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.17960 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.42156 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.10911 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.42387 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.13814 * CGRectGetHeight(page1))];
                [shape4Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.41356 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.28456 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.42387 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.23761 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.41926 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.28456 * CGRectGetHeight(page1))];
                [shape4Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.40719 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.26244 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.41058 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.28456 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.40868 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.27349 * CGRectGetHeight(page1))];
                [shape4Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.38644 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.19614 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.40149 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.22100 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.39539 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.19614 * CGRectGetHeight(page1))];
                [shape4Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.35918 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.49725 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.37125 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.19614 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.35918 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.33287 * CGRectGetHeight(page1))];
                [shape4Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.35918 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50001 * CGRectGetHeight(page1))];
                [shape4Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.38793 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.80662 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.35918 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.67682 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.37112 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.80662 * CGRectGetHeight(page1))];
                [shape4Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.40759 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.74861 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.39553 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.80662 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.40231 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.78728 * CGRectGetHeight(page1))];
                [shape4Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.40759 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.61047 * CGRectGetHeight(page1))];
                [shape4Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.39349 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.61047 * CGRectGetHeight(page1))];
                [shape4Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.38441 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.51932 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.38848 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.61047 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.38441 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.57042 * CGRectGetHeight(page1))];
                [shape4Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.39349 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.42676 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.38441 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.46822 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.38847 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.42676 * CGRectGetHeight(page1))];
                [shape4Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.41736 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.42676 * CGRectGetHeight(page1))];
                [shape4Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.42780 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.53313 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.42319 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.42676 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.42780 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.47374 * CGRectGetHeight(page1))];
                [shape4Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.42780 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.76792 * CGRectGetHeight(page1))];
                [shape4Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.42048 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.90329 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.42780 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.83007 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.42550 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.87288 * CGRectGetHeight(page1))];
                [shape4Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.38725 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.99994 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.41275 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.95163 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.40149 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.99994 * CGRectGetHeight(page1))];
                [shape4Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.33735 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50278 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.35769 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 1.00003 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.33735 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.78872 * CGRectGetHeight(page1))];
                [shape4Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.33735 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50278 * CGRectGetHeight(page1))];
                [shape4Path closePath];
                shape4Path.miterLimit = 4;

                shape4Path.usesEvenOddFillRule = YES;

                [logoTextColor setFill];
                [shape4Path fill];


                //// Shape 5 Drawing
                UIBezierPath* shape5Path = UIBezierPath.bezierPath;
                [shape5Path moveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.46142 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.12295 * CGRectGetHeight(page1))];
                [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.47186 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.01660 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.46142 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.06356 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.46603 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.01660 * CGRectGetHeight(page1))];
                [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.50549 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.01660 * CGRectGetHeight(page1))];
                [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.53030 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.10226 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.51633 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.01660 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.52488 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.04699 * CGRectGetHeight(page1))];
                [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.53681 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.26661 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.53464 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.14645 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.53681 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.20032 * CGRectGetHeight(page1))];
                [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.53681 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.26937 * CGRectGetHeight(page1))];
                [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.52434 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.47797 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.53681 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.37851 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.53111 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.43927 * CGRectGetHeight(page1))];
                [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.54210 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.71552 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.53532 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.52076 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.54210 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.58570 * CGRectGetHeight(page1))];
                [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.54210 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.71829 * CGRectGetHeight(page1))];
                [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.50657 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98348 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.54210 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.89509 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.52800 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98348 * CGRectGetHeight(page1))];
                [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.47186 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98348 * CGRectGetHeight(page1))];
                [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.46142 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.87717 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.46603 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98348 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.46142 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.93653 * CGRectGetHeight(page1))];
                [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.46142 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.12295 * CGRectGetHeight(page1))];
                [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.46142 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.12295 * CGRectGetHeight(page1))];
                [shape5Path closePath];
                [shape5Path moveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.50102 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.40748 * CGRectGetHeight(page1))];
                [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.51607 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.30528 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.51024 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.40748 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.51607 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.37710 * CGRectGetHeight(page1))];
                [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.51607 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.30249 * CGRectGetHeight(page1))];
                [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.50237 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.20305 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.51607 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.23899 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.51118 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.20305 * CGRectGetHeight(page1))];
                [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.48176 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.20305 * CGRectGetHeight(page1))];
                [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.48176 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.40745 * CGRectGetHeight(page1))];
                [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.50102 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.40745 * CGRectGetHeight(page1))];
                [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.50102 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.40748 * CGRectGetHeight(page1))];
                [shape5Path closePath];
                [shape5Path moveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.50657 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.79698 * CGRectGetHeight(page1))];
                [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.52135 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.69202 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.51580 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.79698 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.52135 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.76383 * CGRectGetHeight(page1))];
                [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.52135 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.68925 * CGRectGetHeight(page1))];
                [shape5Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.50589 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.58429 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.52135 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.62434 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.51661 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.58429 * CGRectGetHeight(page1))];
                [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.48176 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.58429 * CGRectGetHeight(page1))];
                [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.48176 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.79701 * CGRectGetHeight(page1))];
                [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.50657 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.79701 * CGRectGetHeight(page1))];
                [shape5Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.50657 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.79698 * CGRectGetHeight(page1))];
                [shape5Path closePath];
                shape5Path.miterLimit = 4;

                shape5Path.usesEvenOddFillRule = YES;

                [logoTextColor setFill];
                [shape5Path fill];


                //// Shape 6 Drawing
                UIBezierPath* shape6Path = UIBezierPath.bezierPath;
                [shape6Path moveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.56867 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50278 * CGRectGetHeight(page1))];
                [shape6Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.56867 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50001 * CGRectGetHeight(page1))];
                [shape6Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.61925 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00000 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.56867 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.22515 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.58996 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00000 * CGRectGetHeight(page1))];
                [shape6Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.66956 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.49725 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.64854 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00000 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.66956 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.22239 * CGRectGetHeight(page1))];
                [shape6Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.66956 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50001 * CGRectGetHeight(page1))];
                [shape6Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.61898 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 1.00000 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.66956 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.77488 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.64827 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 1.00000 * CGRectGetHeight(page1))];
                [shape6Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.56867 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50278 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.58969 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 1.00003 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.56867 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.77764 * CGRectGetHeight(page1))];
                [shape6Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.56867 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50278 * CGRectGetHeight(page1))];
                [shape6Path closePath];
                [shape6Path moveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.64773 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50278 * CGRectGetHeight(page1))];
                [shape6Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.64773 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50001 * CGRectGetHeight(page1))];
                [shape6Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.61898 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.19614 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.64773 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.33425 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.63579 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.19614 * CGRectGetHeight(page1))];
                [shape6Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.59050 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.49725 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.60216 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.19614 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.59050 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.33149 * CGRectGetHeight(page1))];
                [shape6Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.59050 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50001 * CGRectGetHeight(page1))];
                [shape6Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.61925 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.80388 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.59050 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.66575 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.60244 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.80388 * CGRectGetHeight(page1))];
                [shape6Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.64773 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50278 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.63607 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.80388 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.64773 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.66854 * CGRectGetHeight(page1))];
                [shape6Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.64773 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50278 * CGRectGetHeight(page1))];
                [shape6Path closePath];
                shape6Path.miterLimit = 4;

                shape6Path.usesEvenOddFillRule = YES;

                [logoTextColor setFill];
                [shape6Path fill];


                //// Shape 7 Drawing
                UIBezierPath* shape7Path = UIBezierPath.bezierPath;
                [shape7Path moveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.69626 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.81217 * CGRectGetHeight(page1))];
                [shape7Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.72189 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.49173 * CGRectGetHeight(page1))];
                [shape7Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.69776 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.19200 * CGRectGetHeight(page1))];
                [shape7Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.69464 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.11328 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.69613 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.17126 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.69464 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.14366 * CGRectGetHeight(page1))];
                [shape7Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.70494 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00832 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.69464 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.05389 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.69898 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00832 * CGRectGetHeight(page1))];
                [shape7Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.71457 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.06080 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.70942 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00832 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.71199 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.02627 * CGRectGetHeight(page1))];
                [shape7Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.73532 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.34257 * CGRectGetHeight(page1))];
                [shape7Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.75593 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.06632 * CGRectGetHeight(page1))];
                [shape7Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.76610 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00829 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.75878 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.02903 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.76149 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00829 * CGRectGetHeight(page1))];
                [shape7Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.77559 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.10634 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.77071 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.00829 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.77559 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.04560 * CGRectGetHeight(page1))];
                [shape7Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.77247 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.18783 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.77559 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.13676 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.77451 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.16159 * CGRectGetHeight(page1))];
                [shape7Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.74833 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.48894 * CGRectGetHeight(page1))];
                [shape7Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.77383 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.80803 * CGRectGetHeight(page1))];
                [shape7Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.77694 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.88675 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.77545 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.82874 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.77694 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.85637 * CGRectGetHeight(page1))];
                [shape7Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.76664 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.99171 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.77694 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.94614 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.77261 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.99171 * CGRectGetHeight(page1))];
                [shape7Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.75701 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.93923 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.76216 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.99171 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.75959 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.97373 * CGRectGetHeight(page1))];
                [shape7Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.73477 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.64227 * CGRectGetHeight(page1))];
                [shape7Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.71281 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.93371 * CGRectGetHeight(page1))];
                [shape7Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.70263 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.99174 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.70996 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.97100 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.70724 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.99174 * CGRectGetHeight(page1))];
                [shape7Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.69314 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.89368 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.69802 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.99174 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.69314 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.95442 * CGRectGetHeight(page1))];
                [shape7Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.69626 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.81217 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.69314 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.86330 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.69423 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.83841 * CGRectGetHeight(page1))];
                [shape7Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.69626 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.81217 * CGRectGetHeight(page1))];
                [shape7Path closePath];
                shape7Path.miterLimit = 4;

                shape7Path.usesEvenOddFillRule = YES;

                [logoTextColor setFill];
                [shape7Path fill];


                //// Shape 8 Drawing
                UIBezierPath* shape8Path = UIBezierPath.bezierPath;
                [shape8Path moveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.80813 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.87711 * CGRectGetHeight(page1))];
                [shape8Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.80813 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.12295 * CGRectGetHeight(page1))];
                [shape8Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.81857 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.01660 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.80813 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.06356 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.81274 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.01660 * CGRectGetHeight(page1))];
                [shape8Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.87118 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.01660 * CGRectGetHeight(page1))];
                [shape8Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.88054 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.11190 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.87634 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.01660 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.88054 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.05942 * CGRectGetHeight(page1))];
                [shape8Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.87118 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.20584 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.88054 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.16438 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.87634 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.20584 * CGRectGetHeight(page1))];
                [shape8Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.82887 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.20584 * CGRectGetHeight(page1))];
                [shape8Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.82887 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.40196 * CGRectGetHeight(page1))];
                [shape8Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.86508 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.40196 * CGRectGetHeight(page1))];
                [shape8Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.87444 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.49725 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.87023 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.40196 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.87444 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.44477 * CGRectGetHeight(page1))];
                [shape8Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.86508 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.59117 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.87444 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.54973 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.87023 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.59117 * CGRectGetHeight(page1))];
                [shape8Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.82887 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.59117 * CGRectGetHeight(page1))];
                [shape8Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.82887 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.79422 * CGRectGetHeight(page1))];
                [shape8Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.87186 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.79422 * CGRectGetHeight(page1))];
                [shape8Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.88122 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.88951 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.87701 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.79422 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.88122 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.83703 * CGRectGetHeight(page1))];
                [shape8Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.87186 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98343 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.88122 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.94199 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.87701 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98343 * CGRectGetHeight(page1))];
                [shape8Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.81857 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98343 * CGRectGetHeight(page1))];
                [shape8Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.80813 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.87711 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.81274 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98343 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.80813 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.93650 * CGRectGetHeight(page1))];
                [shape8Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.80813 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.87711 * CGRectGetHeight(page1))];
                [shape8Path closePath];
                shape8Path.miterLimit = 4;

                shape8Path.usesEvenOddFillRule = YES;

                [logoTextColor setFill];
                [shape8Path fill];


                //// Shape 9 Drawing
                UIBezierPath* shape9Path = UIBezierPath.bezierPath;
                [shape9Path moveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.91254 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.12295 * CGRectGetHeight(page1))];
                [shape9Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.92298 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.01660 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.91254 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.06356 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.91715 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.01660 * CGRectGetHeight(page1))];
                [shape9Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.94956 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.01660 * CGRectGetHeight(page1))];
                [shape9Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 1.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.49728 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.97939 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.01660 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 1.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.22518 * CGRectGetHeight(page1))];
                [shape9Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 1.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50004 * CGRectGetHeight(page1))];
                [shape9Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.94956 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98346 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 1.00000 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.77215 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.97939 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98346 * CGRectGetHeight(page1))];
                [shape9Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.92298 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98346 * CGRectGetHeight(page1))];
                [shape9Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.91254 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.87714 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.91715 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.98346 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.91254 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.93650 * CGRectGetHeight(page1))];
                [shape9Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.91254 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.12295 * CGRectGetHeight(page1))];
                [shape9Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.91254 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.12295 * CGRectGetHeight(page1))];
                [shape9Path closePath];
                [shape9Path moveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.94956 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.79145 * CGRectGetHeight(page1))];
                [shape9Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.97817 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50278 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.96664 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.79145 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.97817 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.67406 * CGRectGetHeight(page1))];
                [shape9Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.97817 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.50001 * CGRectGetHeight(page1))];
                [shape9Path addCurveToPoint: CGPointMake(CGRectGetMinX(page1) + 0.94956 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.20857 * CGRectGetHeight(page1)) controlPoint1: CGPointMake(CGRectGetMinX(page1) + 0.97817 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.32873 * CGRectGetHeight(page1)) controlPoint2: CGPointMake(CGRectGetMinX(page1) + 0.96664 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.20857 * CGRectGetHeight(page1))];
                [shape9Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.93342 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.20857 * CGRectGetHeight(page1))];
                [shape9Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.93342 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.79145 * CGRectGetHeight(page1))];
                [shape9Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.94956 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.79145 * CGRectGetHeight(page1))];
                [shape9Path addLineToPoint: CGPointMake(CGRectGetMinX(page1) + 0.94956 * CGRectGetWidth(page1), CGRectGetMinY(page1) + 0.79145 * CGRectGetHeight(page1))];
                [shape9Path closePath];
                shape9Path.miterLimit = 4;

                shape9Path.usesEvenOddFillRule = YES;

                [logoTextColor setFill];
                [shape9Path fill];
            }
        }
    }
}

#pragma mark Generated Images

+ (UIImage*)imageOfPlusWithColor: (UIColor*)color width: (CGFloat)width;
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(width, width), NO, 0.0f);
    [PaintCodeImages drawPlusWithColor: color width: width];
    UIImage* imageOfPlus = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfPlus;
}

+ (UIImage*)imageOfArrowWithColor: (UIColor*)color width: (CGFloat)width;
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(width, width), NO, 0.0f);
    [PaintCodeImages drawArrowWithColor: color width: width];
    UIImage* imageOfArrow = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfArrow;
}

+ (UIImage*)imageOfLongboxedLogoWithColor: (UIColor*)color width: (CGFloat)width;
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(width, width), NO, 0.0f);
    [PaintCodeImages drawLongboxedLogoWithColor: color width: width];
    UIImage* imageOfLongboxedLogo = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfLongboxedLogo;
}

+ (UIImage*)imageOfMagnifyingGlassWithColor: (UIColor*)color width: (CGFloat)width;
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(width, width), NO, 0.0f);
    [PaintCodeImages drawMagnifyingGlassWithColor: color width: width];
    UIImage* imageOfMagnifyingGlass = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfMagnifyingGlass;
}

+ (UIImage*)imageOfDefaultCoverWithColor: (UIColor*)color background: (UIColor*)background width: (CGFloat)width height: (CGFloat)height;
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(width, height), NO, 0.0f);
    [PaintCodeImages drawDefaultCoverWithColor: color background: background width: width height: height];
    UIImage* imageOfDefaultCover = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfDefaultCover;
}

+ (UIImage*)imageOfLongboxedTextWithLogoTextColor: (UIColor*)logoTextColor logoWidth: (CGFloat)logoWidth;
{
    UIGraphicsBeginImageContextWithOptions(CGSizeMake(logoWidth, logoWidth/8), NO, 0.0f);
    [PaintCodeImages drawLongboxedTextWithLogoTextColor: logoTextColor logoWidth: logoWidth];
    UIImage* imageOfLongboxedText = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfLongboxedText;
}

@end
