//
//  PaintCodeImages.h
//  Longboxed-iOS
//
//  Created by Jay Hickey on 9/17/14.
//  Copyright (c) 2014 Jay Hickey. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface PaintCodeImages : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* checkmarkTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* longboxedIconTargets;

// Generated Images
+ (UIImage*)imageOfCheckmarkWithFillColor: (UIColor*)fillColor width: (CGFloat)width;
+ (UIImage*)imageOfLongboxedIconWithColor: (UIColor*)color width: (CGFloat)width;

@end
